---
abstract: 'add option keywords to your Moo object'
author:
  - 'Geistteufel <geistteufel@celogeek.fr>'
build_requires:
  English: 0
  File::Find: 0
  File::Temp: 0
  FindBin: 0
  Mo: 0
  Module::Build: 0.3601
  Module::Load::Conditional: 0
  Moo: 0.009013
  Moose: 0
  Mouse: 0
  Scalar::Util: 0
  Test::More: 0.94
  Test::Trap: 0
  Try::Tiny: 0
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300007, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooX-Options
requires:
  Carp: 0
  Data::Dumper: 0
  Data::Record: 0
  Getopt::Long::Descriptive: 0
  Regexp::Common: 0
  perl: 5.010
  strict: 0
  warnings: 0
version: 0.9
